#export cmd="run.pl"
export cmd="queue.pl -q tiger.cpu.q"
export train_cmd="queue.pl -l arch=*64* -q tiger.cpu.q"
#export train_cmd="run.pl"
export gpu_cmd="queue.pl -q tiger.gpu.q"
#export gpu_cmd="run.pl"
